In [6]:

import pandas as pd


df = pd.read_json("imdb_movies_2000to2022.prolific.json", lines=True)


df = df[df['title'].notna()]
df = df[df['genres'].map(lambda x: isinstance(x, list) and len(x) > 0)].reset_index(drop=True)


df[['title', 'genres']].head()

def jaccard_similarity(set1, set2):
    intersection = len(set(set1).intersection(set(set2)))
    union = len(set(set1).union(set(set2)))
    return intersection / union if union > 0 else 0

def find_similar_movies(df, query_title, top_n=10):
    if query_title not in df['title'].values:
        return f"'{query_title}' not found in dataset."

    query_genres = df[df['title'] == query_title].iloc[0]['genres']
    similarities = []

    for idx, row in df.iterrows():
        if row['title'] != query_title:
            sim = jaccard_similarity(query_genres, row['genres'])
            similarities.append((row['title'], sim))

    top_similar = sorted(similarities, key=lambda x: x[1], reverse=True)[:top_n]
    return pd.DataFrame(top_similar, columns=["Similar Movie", "Jaccard Score"])

query_movies = ["Shrek", "Training Day", "Resident Evil"]

for movie in query_movies:
    print(f"\nTop 10 movies similar to '{movie}':")
    display(find_similar_movies(df, movie))

Top 10 movies similar to 'Shrek':

                          Similar Movie  Jaccard Score
0                           Chicken Run            1.0
1              The Emperor's New Groove            1.0
2  The Adventures of Rocky & Bullwinkle            1.0
3                 The Road to El Dorado            1.0
4      Sinbad: Legend of the Seven Seas            1.0
5                        Monsters, Inc.            1.0
6                      Rugrats in Paris            1.0
7                          Finding Nemo            1.0
8                               Ice Age            1.0
9                     The Jungle Book 2            1.0

Top 10 movies similar to 'Training Day':

        Similar Movie  Jaccard Score
0                Gang            1.0
1          15 Minutes            1.0
2          Point Doom            1.0
3          The Skulls            1.0
4   The Wrecking Crew            1.0
5  The Way of the Gun            1.0
6          Get Carter            1.0
7          Turn It Up            1.0
8           Antitrust            1.0
9           The Score            1.0

Top 10 movies similar to 'Resident Evil':

                 Similar Movie  Jaccard Score
0                  Pitch Black            1.0
1                   Hollow Man            1.0
2                     Blade II            1.0
3                      Jason X            1.0
4               Ghosts of Mars            1.0
5                 New Alcatraz            1.0
6                    The Breed            1.0
7  Spiders II: Breeding Ground            1.0
8                 Flying Virus            1.0
9    Resident Evil: Apocalypse            1.0